AWSTemplateFormatVersion: 2010-09-09
Description: One Time Authentication CloudFormation Template between csa and AWS Account
Parameters:
  ExternalId:
    Type: String
  RoleName:
    Type: String
Resources:
  csaWriteManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: CSA Access Policy # CSA inline policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: csa1471737600
            Effect: Allow
            Action:
              - ec2:DescribeReservedInstances
              - ec2:DescribeReservedInstancesListings
              - ec2:DescribeReservedInstancesModifications
              - ec2:DescribeReservedInstancesOfferings
              - ec2:DescribeCapacityReservationFleets
              - ec2:DescribeCapacityReservations
              - ec2:DescribeHostReservationOfferings
              - ec2:DescribeHostReservations
              - ec2:DescribeHosts
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeInstanceTypes
              - ec2:PurchaseReservedInstancesOffering
              - ec2:AcceptReservedInstancesExchangeQuote
              - ec2:GetReservedInstancesExchangeQuote
              - ec2:ModifyReservedInstances
              - ec2:CreateTags
              - savingsplans:DescribeSavingsPlanRates
              - savingsplans:DescribeSavingsPlans
              - savingsplans:DescribeSavingsPlansOfferingRates
              - savingsplans:DescribeSavingsPlansOfferings
              - savingsplans:CreateSavingsPlan
              - ce:GetCostAndUsage
              - ce:GetCostAndUsageWithResources
              - ce:GetDimensionValues
              - ce:GetReservationCoverage
              - ce:GetReservationPurchaseRecommendation
              - ce:GetReservationUtilization
              - ce:GetSavingsPlanPurchaseRecommendationDetails
              - ce:GetSavingsPlansCoverage
              - ce:GetSavingsPlansPurchaseRecommendation
              - ce:GetSavingsPlansUtilization
              - ce:GetSavingsPlansUtilizationDetails
            Resource:
              - "*"
  csaWriteRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::282711413064:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalId
      ManagedPolicyArns:
        - Ref: csaWriteManagedPolicy
      RoleName:
        Ref: RoleName
Outputs:
  csaWriteRoleArn:
    Value:
      Fn::GetAtt:
        - csaWriteRole
        - Arn
